# Generated by Django 2.2.9 on 2020-05-16 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.PostCategory'),
        ),
    ]
